package com.ascend.app;
import android.app.*;import android.content.*;import android.os.*;import android.provider.Settings;import java.util.*;
public final class ScheduleEngine{
 private ScheduleEngine(){}
 public static void rescheduleAll(Context c,List<MainActivity.ScheduleItem> items){AlarmManager am=(AlarmManager)c.getSystemService(Context.ALARM_SERVICE);if(am==null)return;for(MainActivity.ScheduleItem s:items){cancel(c,s.id);Calendar x=next(s);if(Build.VERSION.SDK_INT>=31&&!am.canScheduleExactAlarms()){try{c.startActivity(new Intent(Settings.ACTION_REQUEST_SCHEDULE_EXACT_ALARM));}catch(Exception ignored){}}Intent i=new Intent(c,ScheduleReceiver.class);i.putExtra("title",s.title);i.putExtra("end",MainActivity.fmt(s.end));i.putExtra("start",s.start);i.putExtra("repeat",s.repeat);i.putExtra("id",s.id);PendingIntent p=PendingIntent.getBroadcast(c,s.id,i,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);if(Build.VERSION.SDK_INT>=31&&!am.canScheduleExactAlarms())continue;if(Build.VERSION.SDK_INT>=23)am.setExactAndAllowWhileIdle(AlarmManager.RTC_WAKEUP,x.getTimeInMillis(),p);else am.setExact(AlarmManager.RTC_WAKEUP,x.getTimeInMillis(),p);}}
 public static void cancel(Context c,int id){AlarmManager am=(AlarmManager)c.getSystemService(Context.ALARM_SERVICE);Intent i=new Intent(c,ScheduleReceiver.class);PendingIntent p=PendingIntent.getBroadcast(c,id,i,PendingIntent.FLAG_NO_CREATE|PendingIntent.FLAG_IMMUTABLE);if(am!=null&&p!=null)am.cancel(p);}
 static Calendar next(MainActivity.ScheduleItem s){Calendar now=Calendar.getInstance();Calendar x=Calendar.getInstance();x.set(Calendar.SECOND,0);x.set(Calendar.MILLISECOND,0);x.set(Calendar.HOUR_OF_DAY,s.start/60);x.set(Calendar.MINUTE,s.start%60);for(int k=0;k<8;k++){int d=x.get(Calendar.DAY_OF_WEEK);boolean ok=s.repeat.equals("Every day")||s.repeat.equals("Once")||(s.repeat.equals("Weekdays")&&d>=2&&d<=6)||(s.repeat.equals("Weekend")&&(d==1||d==7));if(ok&&x.after(now))return x;x.add(Calendar.DAY_OF_MONTH,1);}return x;}
 public static void speakNow(Context c,String text){final android.speech.tts.TextToSpeech[] holder=new android.speech.tts.TextToSpeech[1];holder[0]=new android.speech.tts.TextToSpeech(c.getApplicationContext(),st->{if(st==android.speech.tts.TextToSpeech.SUCCESS){holder[0].setLanguage(Locale.US);holder[0].setSpeechRate(1.05f);holder[0].speak(text,android.speech.tts.TextToSpeech.QUEUE_FLUSH,null,"ASCEND_TEST");}});}
}
